name: Main
on:
  workflow_dispatch:

jobs:
  publish_mac:
    name: Publish to Mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20
        
      - name: Build and Release with Electron Forge
        uses: yinxulai/actions-electron-forge@0.05
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
