name: Main
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Make with Electron Forge
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish:
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish
    needs: [lint, build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build and Release with Electron Forge
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
